apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api-deployment
  labels:
    apps: {{ .Release.Name }}-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api
    spec:
      containers:
        - name: api
          image: ghcr.io/twosmallonions/api:latest
          volumeMounts:
            - name: config-volume
              mountPath: /workspace/config
          env:
            - name: SPRING_CONFIG_LOCATION
              value: file:/workspace/config/application.yaml
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-api-config
---
