resources:
  - api.yaml
configMapGenerator:
  - name: tso-api-config
    files:
      - './application.yaml'
  - name: tso-bff-config
    envs:
      - bff.env
  - name: tso-scraper-config
    envs:
      - scraper.env
  - name: caddy-config
    files:
      - './Caddyfile'
  - name: tso-api-env
    envs:
      - api.env
namespace: tso
images:
  - name: ghcr.io/twosmallonions/api
    newTag: "213458e"
  - name: ghcr.io/twosmallonions/bff
    newTag: "9b12494"
  - name: ghcr.io/twosmallonions/tso-scraper
    newTag: "7261abd"
