resources:
  - api.yaml
  - web.yaml
configMapGenerator:
  - name: tso-api-config
    files:
      - './application.yaml'
  - name: tso-bff-config
    envs:
      - bff.env
  - name: tso-scraper-config
    envs:
      - scraper.env
  - name: caddy-config
    files:
      - './Caddyfile'
  - name: tso-api-env
    envs:
      - api.env
namespace: tso
images:
  - name: ghcr.io/twosmallonions/api
    newTag: "17ba196"
  - name: ghcr.io/twosmallonions/bff
    newTag: "2541e2d"
  - name: ghcr.io/twosmallonions/tso-scraper
    newTag: "6142a0b"
  - name: ghcr.io/twosmallonions/web
    newTag: "latest"
