apiVersion: apps/v1
kind: Deployment
metadata:
  name: tso-web
spec:
  selector:
    matchLabels:
      app: tso-web
  template:
    metadata:
      labels:
        app: tso-web
    spec:
      containers:
      - name: tso-web
        image: ghcr.io/twosmallonions/web:latest
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        env:
          - name: PORT
            value: '3000'
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: tso-web-service
spec:
  selector:
    app: tso-web
  ports:
  - port: 80
    targetPort: 3000