apiVersion: apps/v1
kind: Deployment
metadata:
  name: tso-whoami
spec:
  selector:
    matchLabels:
      app: tso-whoami
  template:
    metadata:
      labels:
        app: tso-whoami
    spec:
      containers:
      - name: tso-whoami
        image: traefik/whoami
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tso-whoami-service
spec:
  selector:
    app: tso-whoami
  ports:
  - port: 80
    targetPort: 80
