name: Update image tag to latest git commit

env:
  KUSTOMIZATION_YAML: "./twosmallonions/kustomization.yaml"

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'The image to update the tag of'
        required: true
        type: string
      tag:
        description: 'The tag to update to'
        required: true
        type: string

jobs:
  update:
    name: Update tags
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          yq -e ".images[] | select(.name==\"$IMAGE\")" ./twosmallonions/kustomization.yaml > /dev/null
          yq -i "(.images[] | select(.name==\"$IMAGE\") | .newTag) |= \"$TAG\"" ./twosmallonions/kustomization.yaml
        env:
          IMAGE: ${{ inputs.image }}
          TAG: ${{ inputs.tag }}
        name: Update tag
      - run: |
          git config --global user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add twosmallonions/kustomization.yaml
          git commit -m "Update $IMAGE to tag $TAG"
          git push
        env:
          IMAGE: ${{ inputs.image }}
          TAG: ${{ inputs.tag }}